// coverage:ignore-file
// Autogenerated from Pigeon (v26.1.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class AnnotationsError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "AnnotationsError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? AnnotationsError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPdfAnnotations(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPdfAnnotations(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPdfAnnotations(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPdfAnnotations(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPdfAnnotations(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPdfAnnotations(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct AnnotationData: Hashable {
  var fileName: String
  var drawingPaths: [[String: Any]]? = nil
  var textAnnotations: [[String: Any]]? = nil
  var pdfPageWidth: Double
  var pdfPageHeight: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnnotationData? {
    let fileName = pigeonVar_list[0] as! String
    let drawingPaths: [[String: Any]]? = nilOrValue(pigeonVar_list[1])
    let textAnnotations: [[String: Any]]? = nilOrValue(pigeonVar_list[2])
    let pdfPageWidth = pigeonVar_list[3] as! Double
    let pdfPageHeight = pigeonVar_list[4] as! Double

    return AnnotationData(
      fileName: fileName,
      drawingPaths: drawingPaths,
      textAnnotations: textAnnotations,
      pdfPageWidth: pdfPageWidth,
      pdfPageHeight: pdfPageHeight
    )
  }
  func toList() -> [Any?] {
    return [
      fileName,
      drawingPaths,
      textAnnotations,
      pdfPageWidth,
      pdfPageHeight,
    ]
  }
  static func == (lhs: AnnotationData, rhs: AnnotationData) -> Bool {
    return deepEqualsPdfAnnotations(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPdfAnnotations(value: toList(), hasher: &hasher)
  }
}

private class PdfAnnotationsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AnnotationData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PdfAnnotationsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AnnotationData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PdfAnnotationsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PdfAnnotationsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PdfAnnotationsPigeonCodecWriter(data: data)
  }
}

class PdfAnnotationsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PdfAnnotationsPigeonCodec(readerWriter: PdfAnnotationsPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PdfAnnotationsApi {
  func registerFonts(fontList: [String]) throws -> Bool
  func addAnnotations(annotationData: AnnotationData) throws -> Bool
  func undoAnnotation(fileName: String, pageNo: Int64) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PdfAnnotationsApiSetup {
  static var codec: FlutterStandardMessageCodec { PdfAnnotationsPigeonCodec.shared }
  /// Sets up an instance of `PdfAnnotationsApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PdfAnnotationsApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let registerFontsChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.registerFonts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.registerFonts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      registerFontsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fontListArg = args[0] as! [String]
        do {
          let result = try api.registerFonts(fontList: fontListArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerFontsChannel.setMessageHandler(nil)
    }
    let addAnnotationsChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.addAnnotations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.addAnnotations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      addAnnotationsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationDataArg = args[0] as! AnnotationData
        do {
          let result = try api.addAnnotations(annotationData: annotationDataArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAnnotationsChannel.setMessageHandler(nil)
    }
    let undoAnnotationChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.undoAnnotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.undoAnnotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      undoAnnotationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileNameArg = args[0] as! String
        let pageNoArg = args[1] as! Int64
        do {
          let result = try api.undoAnnotation(fileName: fileNameArg, pageNo: pageNoArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      undoAnnotationChannel.setMessageHandler(nil)
    }
  }
}
