// coverage:ignore-file
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class AnnotationsError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "AnnotationsError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? AnnotationsError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPdfAnnotations(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPdfAnnotations(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPdfAnnotations(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPdfAnnotations(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPdfAnnotations(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPdfAnnotations(lhsKey, rhsKey) {
          if deepEqualsPdfAnnotations(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPdfAnnotations(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPdfAnnotations(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPdfAnnotations(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPdfAnnotations(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPdfAnnotations(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPdfAnnotations(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPdfAnnotations(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct AnnotationData: Hashable {
  var fileName: String
  var drawingPaths: [[String: Any]]? = nil
  var textAnnotations: [[String: Any]]? = nil
  var pdfPageWidth: Double
  var pdfPageHeight: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnnotationData? {
    let fileName = pigeonVar_list[0] as! String
    let drawingPaths: [[String: Any]]? = nilOrValue(pigeonVar_list[1])
    let textAnnotations: [[String: Any]]? = nilOrValue(pigeonVar_list[2])
    let pdfPageWidth = pigeonVar_list[3] as! Double
    let pdfPageHeight = pigeonVar_list[4] as! Double

    return AnnotationData(
      fileName: fileName,
      drawingPaths: drawingPaths,
      textAnnotations: textAnnotations,
      pdfPageWidth: pdfPageWidth,
      pdfPageHeight: pdfPageHeight
    )
  }
  func toList() -> [Any?] {
    return [
      fileName,
      drawingPaths,
      textAnnotations,
      pdfPageWidth,
      pdfPageHeight,
    ]
  }
  static func == (lhs: AnnotationData, rhs: AnnotationData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPdfAnnotations(lhs.fileName, rhs.fileName) && deepEqualsPdfAnnotations(lhs.drawingPaths, rhs.drawingPaths) && deepEqualsPdfAnnotations(lhs.textAnnotations, rhs.textAnnotations) && deepEqualsPdfAnnotations(lhs.pdfPageWidth, rhs.pdfPageWidth) && deepEqualsPdfAnnotations(lhs.pdfPageHeight, rhs.pdfPageHeight)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnnotationData")
    deepHashPdfAnnotations(value: fileName, hasher: &hasher)
    deepHashPdfAnnotations(value: drawingPaths, hasher: &hasher)
    deepHashPdfAnnotations(value: textAnnotations, hasher: &hasher)
    deepHashPdfAnnotations(value: pdfPageWidth, hasher: &hasher)
    deepHashPdfAnnotations(value: pdfPageHeight, hasher: &hasher)
  }
}

private class PdfAnnotationsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AnnotationData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PdfAnnotationsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AnnotationData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PdfAnnotationsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PdfAnnotationsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PdfAnnotationsPigeonCodecWriter(data: data)
  }
}

class PdfAnnotationsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PdfAnnotationsPigeonCodec(readerWriter: PdfAnnotationsPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PdfAnnotationsApi {
  func registerFonts(fontList: [String]) throws -> Bool
  func addAnnotations(annotationData: AnnotationData) throws -> Bool
  func undoAnnotation(fileName: String, pageNo: Int64) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PdfAnnotationsApiSetup {
  static var codec: FlutterStandardMessageCodec { PdfAnnotationsPigeonCodec.shared }
  /// Sets up an instance of `PdfAnnotationsApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PdfAnnotationsApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let registerFontsChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.registerFonts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.registerFonts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      registerFontsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fontListArg = args[0] as! [String]
        do {
          let result = try api.registerFonts(fontList: fontListArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerFontsChannel.setMessageHandler(nil)
    }
    let addAnnotationsChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.addAnnotations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.addAnnotations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      addAnnotationsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationDataArg = args[0] as! AnnotationData
        do {
          let result = try api.addAnnotations(annotationData: annotationDataArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAnnotationsChannel.setMessageHandler(nil)
    }
    let undoAnnotationChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.undoAnnotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotationsApi.undoAnnotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      undoAnnotationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileNameArg = args[0] as! String
        let pageNoArg = args[1] as! Int64
        do {
          let result = try api.undoAnnotation(fileName: fileNameArg, pageNo: pageNoArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      undoAnnotationChannel.setMessageHandler(nil)
    }
  }
}
