// Autogenerated from Pigeon (v22.7.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class AnnotationsError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "AnnotationsError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? AnnotationsError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnnotationData {
  var fileName: String
  var drawingPaths: [[String: Any]?]
  var textAnnotations: [[String: Any]?]
  var pdfPageWidth: Double
  var pdfPageHeight: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnnotationData? {
    let fileName = pigeonVar_list[0] as! String
    let drawingPaths = pigeonVar_list[1] as! [[String: Any]?]
    let textAnnotations = pigeonVar_list[2] as! [[String: Any]?]
    let pdfPageWidth = pigeonVar_list[3] as! Double
    let pdfPageHeight = pigeonVar_list[4] as! Double

    return AnnotationData(
      fileName: fileName,
      drawingPaths: drawingPaths,
      textAnnotations: textAnnotations,
      pdfPageWidth: pdfPageWidth,
      pdfPageHeight: pdfPageHeight
    )
  }
  func toList() -> [Any?] {
    return [
      fileName,
      drawingPaths,
      textAnnotations,
      pdfPageWidth,
      pdfPageHeight,
    ]
  }
}

private class PdfAnnotationsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AnnotationData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PdfAnnotationsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AnnotationData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PdfAnnotationsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PdfAnnotationsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PdfAnnotationsPigeonCodecWriter(data: data)
  }
}

class PdfAnnotationsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PdfAnnotationsPigeonCodec(readerWriter: PdfAnnotationsPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PdfAnnotations {
  func registerFonts(fontList: [String]) throws -> Bool
  func addAnnotations(annotationData: AnnotationData) throws -> Bool
  func undoAnnotation(fileName: String, pageNo: Int64) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PdfAnnotationsSetup {
  static var codec: FlutterStandardMessageCodec { PdfAnnotationsPigeonCodec.shared }
  /// Sets up an instance of `PdfAnnotations` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PdfAnnotations?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let registerFontsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotations.registerFonts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerFontsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fontListArg = args[0] as! [String]
        do {
          let result = try api.registerFonts(fontList: fontListArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerFontsChannel.setMessageHandler(nil)
    }
    let addAnnotationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotations.addAnnotations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAnnotationsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationDataArg = args[0] as! AnnotationData
        do {
          let result = try api.addAnnotations(annotationData: annotationDataArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAnnotationsChannel.setMessageHandler(nil)
    }
    let undoAnnotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pdf_annotations.PdfAnnotations.undoAnnotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      undoAnnotationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileNameArg = args[0] as! String
        let pageNoArg = args[1] as! Int64
        do {
          let result = try api.undoAnnotation(fileName: fileNameArg, pageNo: pageNoArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      undoAnnotationChannel.setMessageHandler(nil)
    }
  }
}
