name: pdf_annotations
description: "A plugin that enables adding text and freehand annotations to existing pdfs"
version: 1.0.0
homepage: https://github.com/JaseElder
publish_to: none


environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview:
#    git: https://github.com/JaseElder/flutter_pdfview.git
    path: /Users/jasonelder/Documents/Flutter/flutter_pdfview
  collection: any
  path: ^1.9.1
  path_provider: ^2.1.5
  native_device_orientation: ^2.1.0
  nanoid: ^1.0.0
  transparent_pointer: ^1.0.1
  logger: ^2.6.2
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.1.7
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.loucheindustries.pdf_annotations
        pluginClass: PdfAnnotationsPlugin
      ios:
        pluginClass: PdfAnnotationsPlugin
