// Autogenerated from Pigeon (v22.7.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.loucheindustries.pdf_annotations

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class AnnotationData (
  val fileName: String,
  val drawingPaths: List<Map<String, Any>?>,
  val textAnnotations: List<Map<String, Any>?>,
  val pdfPageWidth: Double,
  val pdfPageHeight: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnnotationData {
      val fileName = pigeonVar_list[0] as String
      val drawingPaths = pigeonVar_list[1] as List<Map<String, Any>?>
      val textAnnotations = pigeonVar_list[2] as List<Map<String, Any>?>
      val pdfPageWidth = pigeonVar_list[3] as Double
      val pdfPageHeight = pigeonVar_list[4] as Double
      return AnnotationData(fileName, drawingPaths, textAnnotations, pdfPageWidth, pdfPageHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fileName,
      drawingPaths,
      textAnnotations,
      pdfPageWidth,
      pdfPageHeight,
    )
  }
}
private open class PdfAnnotationsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnnotationData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AnnotationData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PdfAnnotations {
  fun registerFonts(fontList: List<String>): Boolean
  fun addAnnotations(annotationData: AnnotationData): Boolean
  fun undoAnnotation(fileName: String, pageNo: Long): Boolean

  companion object {
    /** The codec used by PdfAnnotations. */
    val codec: MessageCodec<Any?> by lazy {
      PdfAnnotationsPigeonCodec()
    }
    /** Sets up an instance of `PdfAnnotations` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PdfAnnotations?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdf_annotations.PdfAnnotations.registerFonts$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fontListArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.registerFonts(fontListArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdf_annotations.PdfAnnotations.addAnnotations$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val annotationDataArg = args[0] as AnnotationData
            val wrapped: List<Any?> = try {
              listOf(api.addAnnotations(annotationDataArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pdf_annotations.PdfAnnotations.undoAnnotation$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            val pageNoArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.undoAnnotation(fileNameArg, pageNoArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
